### PR TITLE
Backport 4a19c1a65107202800bf8df51684f7255d6ef027

### PR DESCRIPTION
**Pull request by gnu-andrew**

### CODE REVIEW

**Comment by erikj79** [comment]
Skara can't handle this PR due to .jcheck/conf missing in the target branch. I know this did work in jdk8u-dev, and I have no idea why. I haven't seen it work anywhere else before that. I recommend you push .jcheck/conf manually without a PR.

**Review by erikj79 — APPROVED** [review]

**Comment by gnu-andrew** [comment]
Thanks Erik. I thought we might have to push this manually, but it seemed worth a try. The difference between this repository and jdk8u-dev is the latter did have a `.jcheck/conf` file, though a very bare bones Mercurial one. It was deleted altogether from the Shenandoah repository to stop local jcheck complaining.

I don't know if it's worth / possible to have SKARA at least report the failure on the PR, rather than just being silent. I guess it's not really an issue once all projects have transitioned.

**Comment by erikj79** [comment]
Filed https://bugs.openjdk.java.net/browse/SKARA-1393, but as usual, can't promise that when or if it will get fixed.

**Comment by gnu-andrew** [comment]
> Filed https://bugs.openjdk.java.net/browse/SKARA-1393, but as usual, can't promise that when or if it will get fixed.

Thanks Erik, it's appreciated.

**Pull request merged**
