### PR TITLE
8253424: Add support for running pre-submit testing using GitHub Actions

### PR DESCRIPTION
**Pull request by gnu-andrew**
Hi all,

This pull request contains a backport of commit [10029f78](https://github.com/openjdk/jdk8u-dev/commit/10029f784ef7be458a7b6ff3cc21649ff0abb6f3) from the [openjdk/jdk8u-dev](https://git.openjdk.java.net/jdk8u-dev) repository, which enables GitHub Actions for the Shenandoah 8u fork.

The commit being backported was authored by Andrew John Hughes on 6 Apr 2022 and was reviewed by Severin Gehwolf.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issues
 * [JDK-8253424](https://bugs.openjdk.org/browse/JDK-8253424): Add support for running pre-submit testing using GitHub Actions
 * [JDK-8253865](https://bugs.openjdk.org/browse/JDK-8253865): Pre-submit testing using GitHub Actions does not detect failures reliably
 * [JDK-8254054](https://bugs.openjdk.org/browse/JDK-8254054): Pre-submit testing using GitHub Actions should not use the deprecated set-env command
 * [JDK-8254173](https://bugs.openjdk.org/browse/JDK-8254173): Add Zero, Minimal hotspot targets to submit workflow
 * [JDK-8254175](https://bugs.openjdk.org/browse/JDK-8254175): Build no-pch configuration in debug mode for submit checks
 * [JDK-8254282](https://bugs.openjdk.org/browse/JDK-8254282): Add Linux x86_32 builds to submit workflow
 * [JDK-8255373](https://bugs.openjdk.org/browse/JDK-8255373): Submit workflow artifact name is always "test-results_.zip"
 * [JDK-8255895](https://bugs.openjdk.org/browse/JDK-8255895): Submit workflow artifacts miss hs_errs/replays due to ZIP include mismatch
 * [JDK-8256127](https://bugs.openjdk.org/browse/JDK-8256127): Add cross-compiled foreign architectures builds to submit workflow
 * [JDK-8256277](https://bugs.openjdk.org/browse/JDK-8256277): Github Action build on macOS should define OS and Xcode versions
 * [JDK-8256354](https://bugs.openjdk.org/browse/JDK-8256354): Github Action build on Windows should define OS and MSVC versions
 * [JDK-8256414](https://bugs.openjdk.org/browse/JDK-8256414): add optimized build to submit workflow
 * [JDK-8256393](https://bugs.openjdk.org/browse/JDK-8256393): Github Actions build on Linux should define OS and GCC versions
 * [JDK-8256747](https://bugs.openjdk.org/browse/JDK-8256747): GitHub Actions: decouple the hotspot build-only jobs from Linux x64 testing
 * [JDK-8257056](https://bugs.openjdk.org/browse/JDK-8257056): Submit workflow should apt-get update to avoid package installation errors
 * [JDK-8259924](https://bugs.openjdk.org/browse/JDK-8259924): GitHub actions fail on Linux x86_32 with "Could not configure libc6:i386"
 * [JDK-8260460](https://bugs.openjdk.org/browse/JDK-8260460): GitHub actions still fail on Linux x86_32 with "Could not configure libc6:i386"
 * [JDK-8263667](https://bugs.openjdk.org/browse/JDK-8263667): Avoid running GitHub actions on branches named pr/*
 * [JDK-8255305](https://bugs.openjdk.org/browse/JDK-8255305): Add Linux x86_32 tier1 to submit workflow
 * [JDK-8255352](https://bugs.openjdk.org/browse/JDK-8255352): Archive important test outputs in submit workflow
 * [JDK-8282225](https://bugs.openjdk.org/browse/JDK-8282225): GHA: Allow one concurrent run per PR only
 * [JDK-8241768](https://bugs.openjdk.org/browse/JDK-8241768): git needs .gitattributes
 * [JDK-8284772](https://bugs.openjdk.org/browse/JDK-8284772): 8u GHA: Use GCC Major Version Dependencies Only

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah-jdk8u pull/3/head:pull/3` \
`$ git checkout pull/3`

Update a local copy of the PR: \
`$ git checkout pull/3` \
`$ git pull https://git.openjdk.org/shenandoah-jdk8u pull/3/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3`

View PR using the GUI difftool: \
`$ git pr show -t 3`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah-jdk8u/pull/3.diff">https://git.openjdk.org/shenandoah-jdk8u/pull/3.diff</a>

</details>

### CODE REVIEW

**Comment by erikj79** [comment]
The .jcheck/conf file is still broken in this repo. Please run `git jcheck` in locally in the repo to see the exception.

**Comment by gnu-andrew** [comment]
> The .jcheck/conf file is still broken in this repo. Please run `git jcheck` in locally in the repo to see the exception.

I have. I've fixed it locally and in this PR, but `jcheck` only picks it up when it's applied to the `master` branch. I guess I'll have to do another direct push with it. I'm waiting on ops to add `shenandoah8u332` to the list of JBS versions.

**Comment by gnu-andrew** [comment]
`git jcheck` is now passing locally. Will it re-run on this PR?

**Review by shipilev — COMMENTED** [review]
Well, I don't see it running cleanly, so there seems to be no point in pushing it just yet. Was that intermittent? Can we run the GHA again for this PR?

There is also `.github/workflows/freetype.vcxproj` file in this PR, which seems superfluous.

**Comment by gnu-andrew** [comment]
> Well, I don't see it running cleanly, so there seems to be no point in pushing it just yet. Was that intermittent? Can we run the GHA again for this PR?

Thanks for looking.

The Windows failure seems to be an intermittent failure in downloading Visual Studio and indeed it failed only for `release` and not `debug`.  It passed on an earlier run: https://github.com/gnu-andrew/shenandoah-jdk8u/actions/runs/2267320655 and the only recent changes have been to the `.jcheck` configuration.

The MacOS failure is a genuine failure in the Shenandoah 8u code on MacOS. I guess it's never been built there before. I think fixing that is either something to be done in a separate fix (not this backport) or we can decide to just exclude MacOS on Shenandoah 8u.

Failure is:

~~~
/Users/runner/work/shenandoah-jdk8u/shenandoah-jdk8u/jdk/hotspot/src/share/vm/gc_implementation/shenandoah/shenandoahControlThread.cpp:357:25: error: no matching function for call to 'load_acquire'
  size_t new_soft_max = OrderAccess::load_acquire(&ShenandoahSoftMaxHeapSize);
~~~


> 
> There is also `.github/workflows/freetype.vcxproj` file in this PR, which seems superfluous.

This is used to build FreeType on Windows. It's not part of the JDK tree for 8u (something I may look at changing). Everything here is the same as in jdk8u, where all builds pass. My intention with this change was to bring the GHA changes down early so we could test the 8u332 Shenandoah merge, but these same changes will also come in when we merge in 8u342. Of course, when I opened this originally, there was no 8u342 :)

**Review by shipilev — APPROVED** [review]

**Pull request closed without merging**
